openapi: 3.0.0
info:
  title: 'Lumen Cafe API'
  version: '0.1'
paths:
  /products:
    get:
      summary: 'List all products.'
      description: 'Returns all stored products with pagination.'
      responses:
        '200':
          description: 'Array of products'
        '404':
          description: 'Could Not Find Resource'
